from .models.listing import Listing

MOCK_LISTINGS: list[Listing] = [
    Listing(
        id="mock001",
        source="propertyguru",
        title="Spacious 2BR Condo @ Orchard Road",
        url="https://www.propertyguru.com.sg",
        price=3800,
        address="Orchard Road, District 9",
        district="D9",
        lat=1.3048,
        lng=103.8318,
        bedrooms=2,
        bathrooms=2,
        area_sqft=850,
        property_type="Condo",
        furnishing="Fully Furnished",
        amenities=["Pool", "Gym", "Near MRT"],
        images=["https://picsum.photos/seed/condo1/400/300"],
    ),
    Listing(
        id="mock002",
        source="99co",
        title="Cozy 1BR HDB near Bishan MRT",
        url="https://www.99.co",
        price=2000,
        address="Bishan Street 22, District 20",
        district="D20",
        lat=1.3510,
        lng=103.8480,
        bedrooms=1,
        bathrooms=1,
        area_sqft=500,
        property_type="HDB",
        furnishing="Partially Furnished",
        amenities=["Near MRT", "Near Market"],
        images=["https://picsum.photos/seed/hdb1/400/300"],
    ),
    Listing(
        id="mock003",
        source="propertyguru",
        title="Luxury 3BR Condo @ Marina Bay",
        url="https://www.propertyguru.com.sg",
        price=7500,
        address="Marina Boulevard, District 1",
        district="D1",
        lat=1.2789,
        lng=103.8536,
        bedrooms=3,
        bathrooms=3,
        area_sqft=1400,
        property_type="Condo",
        furnishing="Fully Furnished",
        amenities=["Pool", "Gym", "Concierge", "Sea View", "Near MRT"],
        images=["https://picsum.photos/seed/condo2/400/300"],
    ),
    Listing(
        id="mock004",
        source="99co",
        title="Bright 2BR HDB @ Tampines",
        url="https://www.99.co",
        price=2400,
        address="Tampines Street 45, District 18",
        district="D18",
        lat=1.3496,
        lng=103.9568,
        bedrooms=2,
        bathrooms=1,
        area_sqft=700,
        property_type="HDB",
        furnishing="Unfurnished",
        amenities=["Near MRT", "Near Mall"],
        images=["https://picsum.photos/seed/hdb2/400/300"],
    ),
    Listing(
        id="mock005",
        source="propertyguru",
        title="Modern Studio @ Tiong Bahru",
        url="https://www.propertyguru.com.sg",
        price=2800,
        address="Tiong Bahru Road, District 3",
        district="D3",
        lat=1.2847,
        lng=103.8271,
        bedrooms=0,
        bathrooms=1,
        area_sqft=400,
        property_type="Condo",
        furnishing="Fully Furnished",
        amenities=["Near MRT", "Cafe Nearby"],
        images=["https://picsum.photos/seed/studio1/400/300"],
    ),
    Listing(
        id="mock006",
        source="99co",
        title="3BR Condo @ Buona Vista",
        url="https://www.99.co",
        price=4500,
        address="Holland Road, District 10",
        district="D10",
        lat=1.3072,
        lng=103.7902,
        bedrooms=3,
        bathrooms=2,
        area_sqft=1100,
        property_type="Condo",
        furnishing="Partially Furnished",
        amenities=["Pool", "Gym", "Near MRT", "Near School"],
        images=["https://picsum.photos/seed/condo3/400/300"],
    ),
    Listing(
        id="mock007",
        source="propertyguru",
        title="Affordable 4BR HDB @ Woodlands",
        url="https://www.propertyguru.com.sg",
        price=2200,
        address="Woodlands Drive 50, District 25",
        district="D25",
        lat=1.4368,
        lng=103.7864,
        bedrooms=4,
        bathrooms=2,
        area_sqft=1000,
        property_type="HDB",
        furnishing="Partially Furnished",
        amenities=["Near MRT", "Near School", "Near Park"],
        images=["https://picsum.photos/seed/hdb3/400/300"],
    ),
    Listing(
        id="mock008",
        source="99co",
        title="Stylish 1BR Condo @ Novena",
        url="https://www.99.co",
        price=3200,
        address="Thomson Road, District 11",
        district="D11",
        lat=1.3200,
        lng=103.8440,
        bedrooms=1,
        bathrooms=1,
        area_sqft=550,
        property_type="Condo",
        furnishing="Fully Furnished",
        amenities=["Pool", "Gym", "Near MRT", "Near Hospital"],
        images=["https://picsum.photos/seed/condo4/400/300"],
    ),
]


def filter_mock(
    listings: list[Listing],
    min_price=None,
    max_price=None,
    bedrooms=None,
    district=None,
    property_type=None,
) -> list[Listing]:
    result = listings
    if min_price:
        result = [l for l in result if l.price >= min_price]
    if max_price:
        result = [l for l in result if l.price <= max_price]
    if bedrooms is not None:
        result = [l for l in result if l.bedrooms == bedrooms]
    if district:
        result = [l for l in result if l.district and district.upper() in l.district.upper()]
    if property_type:
        result = [l for l in result if l.property_type and property_type.lower() in l.property_type.lower()]
    return result
